version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/gestaodescontos_development
    volumes:
      - .:/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestaodescontos_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
